version: '3.8'

services:
  pdns-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: pdns
      POSTGRES_USER: pdns_user
      POSTGRES_PASSWORD: pdns_password
    volumes:
      - pdns-postgres-data:/var/lib/postgresql/data

  pdns-server:
    image: psitrax/powerdns:v4.4.1
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "15001:8081"
    environment:
      - PDNS_gpgsql_host=pdns-db
      - PDNS_gpgsql_port=5432
      - PDNS_gpgsql_user=pdns_user
      - PDNS_gpgsql_password=pdns_password
      - PDNS_gpgsql_dbname=pdns
      - PDNS_launch=gpgsql
      - PDNS_api=yes
      - PDNS_api_key=NzR1MnpMVjlqNWhmbWlq
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=0.0.0.0/0
    depends_on:
      - pdns-db

  pdns-admin:
    image: powerdnsadmin/pda-legacy:v0.4.2
    restart: always
    ports:
      - "15000:80"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://pdns_user:pdns_password@pdns-db:5432/pdns
      - GUNICORN_TIMEOUT=60
      - PDNS_API_URL=http://pdns-server:8081/
      - PDNS_API_KEY=NzR1MnpMVjlqNWhmbWlq
    depends_on:
      - pdns-db
      - pdns-server

  dns-api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DNS_SERVICE_PDNS_API_URL=http://pdns-server:8081
      - DNS_SERVICE_PDNS_API_KEY=NzR1MnpMVjlqNWhmbWlq
      - DNS_SERVICE_ADMIN_USERNAME=admin
      - DNS_SERVICE_ADMIN_PASSWORD=admin
    depends_on:
      - pdns-server

volumes:
  pdns-postgres-data:
