version: '3.8'

services:
  pdns-db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: pdns
      MYSQL_USER: pdns_user
      MYSQL_PASSWORD: pdns_password
      MYSQL_ROOT_PASSWORD: pdns_root_password
    volumes:
      - pdns-mariadb-data:/var/lib/mysql

  pdns-server:
    image: pschiffe/pdns-mysql:alpine
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "15001:8081"
    environment:
      - PDNS_gmysql_host=pdns-db
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=pdns_user
      - PDNS_gmysql_password=pdns_password
      - PDNS_gmysql_dbname=pdns
      - PDNS_api=yes
      - PDNS_api_key=NzR1MnpMVjlqNWhmbWlq
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=0.0.0.0/0
    depends_on:
      - pdns-db

  pdns-admin:
    image: powerdnsadmin/pda-legacy:v0.4.2
    restart: always
    ports:
      - "15000:80"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pdns_user:pdns_password@pdns-db:3306/pdns
      - GUNICORN_TIMEOUT=60
      - PDNS_API_URL=http://pdns-server:8081/
      - PDNS_API_KEY=NzR1MnpMVjlqNWhmbWlq
    depends_on:
      - pdns-db
      - pdns-server

  dns-api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DNS_SERVICE_PDNS_API_URL=http://pdns-server:8081
      - DNS_SERVICE_PDNS_API_KEY=NzR1MnpMVjlqNWhmbWlq
      - DNS_SERVICE_ADMIN_USERNAME=admin
      - DNS_SERVICE_ADMIN_PASSWORD=admin
    depends_on:
      - pdns-server

volumes:
  pdns-mariadb-data:
