apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pdns-server
  name: pdns-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pdns-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: pdns-server
    spec:
      containers:
      - env:
        - name: PDNS_api
          value: yes
        - name: PDNS_api_key
          value: your_secret_api_key
        - name: PDNS_gpgsql_dbname
          value: pdns
        - name: PDNS_gpgsql_host
          value: pdns-db
        - name: PDNS_gpgsql_password
          value: pdns_password
        - name: PDNS_gpgsql_port
          value: "5432"
        - name: PDNS_gpgsql_user
          value: pdns_user
        - name: PDNS_launch
          value: gpgsql
        - name: PDNS_webserver
          value: yes
        - name: PDNS_webserver_address
          value: 0.0.0.0
        - name: PDNS_webserver_allow_from
          value: 0.0.0.0/0
        image: psitrax/powerdns:v4.4.1
        imagePullPolicy: ""
        name: pdns-server
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
